language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.2
  - DJANGO=https://github.com/django/django/tarball/master

install:
  - pip install --use-mirrors $DJANGO
  - pip install --use-mirrors coverage coveralls

script: coverage run -a --branch setup.py test

matrix:
  exclude:
   - python: 3.2
     env: DJANGO=Django==1.4.10
   - python: 3.3
     env: DJANGO=Django==1.4.10

after_success: coveralls
