language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

env:
  - DJANGO="Django>=2.2,<2.3"
  - DJANGO="Django>=3.0,<3.1"
  - DJANGO="Django>=3.2,<3.3"

install:
  - pip install coverage coveralls $DJANGO

script: coverage run -a --branch setup.py test

after_success: coveralls
